### PR TITLE
FIX: Private member access between outer and inner classes

### LINKED ISSUE #379: Private member access between outer and inner classes
I noticed some inner classes' private members were access from the outer class. e.g. in [RecyclerViewScrollEventObservable.java](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding-recyclerview-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/RecyclerViewScrollEventObservable.java#L23)

If you would welcome a fix, I could send a PR as I am reading a lot of the code these days anyway.

### PR DESCRIPTION
**Pull request by oldergod**
Made package-private all private members accessed from inner classes, including tests.

fix #379 

the tests ran fine here: https://travis-ci.org/oldergod/RxBinding/builds/230737839

### CODE REVIEW

File: rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewTest.java [hunk 1]
```diff
@@ -32,16 +30,14 @@
...
-  private ViewInteraction interaction;
+  RecyclerView view;
   private ViewDirtyIdlingResource viewDirtyIdler;
   private View child;
 
   @Before public void setUp() {
     RxRecyclerViewTestActivity activity = activityRule.getActivity();
     view = activity.recyclerView;
     child = new View(activityRule.getActivity());
-    interaction = Espresso.onView(ViewMatchers.withId(android.R.id.primary));
```
Comment (oldergod) [inline rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewTest.java]: This field was not used.

File: rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewAdapterTest.java [hunk 2]
```diff
@@ -36,6 +36,9 @@
   }
 
   private static final class TestRecyclerAdapter extends RecyclerView.Adapter<ViewHolder> {
+    TestRecyclerAdapter() {
```
Comment (OrdonTeam) [inline rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewAdapterTest.java]: Why do we need empty constructor?

Comment (JakeWharton) [inline rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewAdapterTest.java]: Because otherwise it's private

Comment (JakeWharton) [inline rxbinding-recyclerview-v7/src/androidTest/java/com/jakewharton/rxbinding2/support/v7/widget/RxRecyclerViewAdapterTest.java]: Although this is a test and I don't care about synthetic accessors in tests...

**Comment by JakeWharton** [comment]
Thanks!
