### PR TITLE
Fixed RxSwipeRefreshLayoutTest test

### LINKED ISSUE #72: RxSwipeRefreshLayoutTest is flaky on Travis CI
I cannot figure out why this test sometimes fails on Travis CI...

Affected:
 * https://github.com/JakeWharton/RxBinding/pull/90
 * https://github.com/JakeWharton/RxBinding/pull/190
 * https://github.com/JakeWharton/RxBinding/pull/195
 * https://github.com/JakeWharton/RxBinding/pull/209
 * https://github.com/JakeWharton/RxBinding/pull/223
 * https://github.com/JakeWharton/RxBinding/pull/225

### PR DESCRIPTION
**Pull request by skoric**
After examining `RxSwipeRefreshLayoutTest`, it seems that the automatically ran `.setRefresh(false)` (which performs stopping the refresh animation) could happen to be called between the swipe release and the actual loading/refreshing animation, causing the animation to stop and listener never to be called, thus not recorded.

So the solution I did was to post refresh stop 2 seconds after the first touch on a view happens (which is enough time for the swipe - 1500ms and the recorder to catch up the listener). This should avoid flakyness in this test.

Fixes #72.

### CODE REVIEW

File: rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java [hunk 1]
```diff
@@ -18,15 +21,21 @@
...
 
   @Override protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
 
     swipeRefreshLayout = new SwipeRefreshLayout(this);
-    swipeRefreshLayout.setId(1);
+    swipeRefreshLayout.setId(R.id.swipe_refresh_layout);
+    swipeRefreshLayout.setOnTouchListener(new View.OnTouchListener() {
+      @Override public boolean onTouch(View v, MotionEvent event) {
+        handler.removeCallbacks(stopRefreshing);
```
Comment (JakeWharton) [inline rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java]: What if we only did all this on `ACTION_UP`? That would let keep a short delay like 200ms, right?

**Comment by JakeWharton** [comment]
Nice work. This looks good. I just have potential improvement and then let's get this merged.

File: rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java (hunk 1 above)
Comment (skoric) [inline rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java]: Yes, we could do it on `ACTION_UP` as well with shorter delay, that way we also get flexibility for swipe speeds. Want me to do it that way?

Comment (JakeWharton) [inline rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java]: Please!

File: rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java [hunk 2]
```diff
@@ -18,15 +22,23 @@
...
     super.onCreate(savedInstanceState);
 
     swipeRefreshLayout = new SwipeRefreshLayout(this);
-    swipeRefreshLayout.setId(1);
+    swipeRefreshLayout.setId(R.id.swipe_refresh_layout);
+    swipeRefreshLayout.setOnTouchListener(new View.OnTouchListener() {
+      @Override public boolean onTouch(View v, MotionEvent event) {
+        if (MotionEventCompat.getActionMasked(event) == MotionEvent.ACTION_UP) {
+          handler.removeCallbacks(stopRefreshing);
+          handler.postDelayed(stopRefreshing, 300);
```
Comment (skoric) [inline rxbinding-support-v4/src/androidTest/java/com/jakewharton/rxbinding/support/v4/widget/RxSwipeRefreshLayoutTestActivity.java]: @JakeWharton Used `300`, `200` seemed a bit too fast.

**Comment by JakeWharton** [comment]
Thanks!
