### PR TITLE
Send main thread checks to onError()

### LINKED ISSUE #353: verifyMainThread() checks in RxJava 2 variants don't go to onError
Note sure if this is by design or not, but the exceptions thrown by `verifyMainThread()` fail hard rather than going to `onError()` (since it doesn't know the disposed state during the calling `subscribe` and will just bubble it straight to `RxJavaPlugins#onError()` or throw. Since we have the observer there, should we send the exception to its onError() instead? 

Specifically, I think this is actually a significant behavior change from the implementation in RxJava 1 or using `create()`, which _would_ send this to `onError()`.

Result is if you want to gracefully handle that case, you end up having to try/catch the actual subscribe() call itself

### PR DESCRIPTION
**Pull request by hzsweers**
This ensures they go through onError implementations rather than failing hard. Resolves #353

### CODE REVIEW

**Comment by hzsweers** [comment]
Wasn't sure if `Preconditions` was a good place for this, can move if necessary

File: rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java [hunk 1]
```diff
@@ -27,6 +30,15 @@ public static void checkArgument(boolean assertion, String message) {
     return value;
   }
 
+  public static boolean isNotOnMainThread(Observer<?> observer) {
```
Comment (OrdonTeam) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: I don't like this name. I was surprised `isSomething` method not only checks condition but also emit error to observer.

Comment (hzsweers) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: Maybe, have an alternate suggestion?

Comment (OrdonTeam) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: I would split it to two methods.
`isMainThread` which would only check
and second which would send error to observer.

Comment (OrdonTeam) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: `if (isNotOnMainThread()) {`
 `      emitNotMainthreadError(observer);`
 `} else {

Comment (dlew) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: `requireMainThreadOrError()`?

Comment (OrdonTeam) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: is an option

Comment (hzsweers) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: Trying to keep it simple. @dlew what would `requireMainThreadOrError()` return?

Comment (JakeWharton) [inline rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java]: Definitely not two methods. How about just `checkMainThread` with a boolean not placed at each call site to negate the result.
